# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: jekyll/jekyll:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and deploy
        run: |
          mkdir -p ./docs/_site
          mkdir -p /tmp/.jekyll-cache
          jekyll build -s ./docs -d ./docs/_site --trace --config ./docs/_config.yml,./docs/_config_ci.yml
          touch ./docs/_site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
